# Generated by Django 3.2.25 on 2024-10-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('square_meters', models.DecimalField(decimal_places=2, max_digits=6)),
                ('property_type', models.CharField(choices=[('house', 'Casa'), ('cabin', 'Cabaña'), ('apartment', 'Apartamento'), ('studio', 'Estudio'), ('land', 'Terreno')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
