# Generated by Django 3.2.4 on 2024-11-07 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Finanzas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planes_de_financiamiento', models.CharField(choices=[('hab', 'Habitacional'), ('alq', 'Alquiler'), ('inv_conjunta', 'Inversión Conjunta')], max_length=20, verbose_name='Planes de financiamiento')),
                ('tipo_de_inversion', models.CharField(choices=[('hab', 'Habitacional'), ('alq', 'Alquiler'), ('inv_conjunta', 'Inversión Conjunta')], max_length=20, verbose_name='Tipo de inversión')),
                ('tipo_de_moneda', models.CharField(choices=[('usd', 'Dólar'), ('eur', 'Euro'), ('crypto', 'Cripto')], max_length=10, verbose_name='Tipo de moneda')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='num_bedrooms',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='num_rooms',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='project_category',
            field=models.CharField(choices=[('social', 'Interés Social'), ('luxury', 'Luxury'), ('premium', 'Premium')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='project_type',
            field=models.CharField(choices=[('pozo', 'Pozo'), ('no_pozo', 'No Pozo')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='residence_type',
            field=models.CharField(choices=[('familiar', 'Familiar'), ('unipersonal', 'Unipersonal'), ('universitaria', 'Universitaria')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='chat.country')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='chat.province')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='chat.city'),
        ),
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='chat.country'),
        ),
        migrations.AddField(
            model_name='property',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='chat.province'),
        ),
    ]
