# Generated by Django 3.2.25 on 2024-12-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
